### ISSUE TITLE
Conditional  send alert

### ISSUE THREAD

**Issue by Simdrom** [Caraxi/AdventurerInNeed#1]
Hi,
I was thinking if it would be possible to add a condition, adding one more check boxes to the list of send  conditions (send alets in game chat and where, and send alert to webhook and setup webhooks) that would be:

- [ ] Send done Adventurer in Need alerts

Like this, for example, if i've done Leveling, it wouldnt appear more in my preferred channel until the next reset.

Regards,
Simdrom

**Comment by vehrmii** [comment]
+1 Would appreciate this feature since my role does often go in need for certain roulettes.

**Comment by BSoD38** [comment]
I'd appreciate the ability to disable the alerts if the roulette has already been done as well.

**Comment by GunB** [comment]
+1 This is exactly what I wanted to say. Really would love the option to condition the alerts up to when the bonus has been claimed.

**Comment by Diorik** [comment]
+1 The eternal struggle between disabling AIN after doing roulettes or suffering the spam so I don't forget to turn it on again.

**Comment by gurkburk76** [comment]
I was about to suggest the exact same thing, not sure if the author is still working on the plugin?

**Comment by Caraxi** [comment]
better 2 and a half years later than never?
Will be available in 6.5
