### ISSUE TITLE
doesn't work at all

### ISSUE THREAD

**Issue by nammerduong** [Caraxi/AdventurerInNeed#7]
Am I the only one that can't get this thing to work? I literally checked every position on all the roulettes and never get an alert when the role changes. I even set the "send alerts in game chat" to "any" and a bunch of others and still nothing.

**Comment by christopherjtaylor** [comment]
> Am I the only one that can't get this thing to work? I literally checked every position on all the roulettes and never get an alert when the role changes. I even set the "send alerts in game chat" to "any" and a bunch of others and still nothing.

Potentially dumb question, but did you check the boxes to the left of the Duty names? I came here with a similar question, but realized I checked the roles but didn't actually enable the duties with their specific checkboxes. Hope this helps!

**Comment by Sebdevar** [comment]
I can second the issue report, I have everything check except the webhook and I'm not getting anything, whatever chat selection I put
