### ISSUE TITLE
Only recive alerts under certain conditions

### ISSUE THREAD

**Issue by gurkburk76** [Caraxi/AdventurerInNeed#8]
Heya, not sure if this plugin is still being worked on, but here goes my request :)

I'de like it to be configurable so i recive alerts for things like daily roulettes etc, but only if i haven't actually clear it for the day.
Simply, i'de like to be able to choose :)

**Comment by Caraxi** [comment]
5616ff79c41e0ffdc40de31a9f898aeb3cae5d8b
